function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Motor_Model__Discrete_Example"};
	this.sidHashMap["Motor_Model__Discrete_Example"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Motor_Model__Discrete_Example:18"};
	this.sidHashMap["Motor_Model__Discrete_Example:18"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Voltage"] = {sid: "Motor_Model__Discrete_Example:28"};
	this.sidHashMap["Motor_Model__Discrete_Example:28"] = {rtwname: "<Root>/Voltage"};
	this.rtwnameHashMap["<Root>/DC Motor"] = {sid: "Motor_Model__Discrete_Example:18"};
	this.sidHashMap["Motor_Model__Discrete_Example:18"] = {rtwname: "<Root>/DC Motor"};
	this.rtwnameHashMap["<Root>/Speed"] = {sid: "Motor_Model__Discrete_Example:29"};
	this.sidHashMap["Motor_Model__Discrete_Example:29"] = {rtwname: "<Root>/Speed"};
	this.rtwnameHashMap["<S1>/Voltage"] = {sid: "Motor_Model__Discrete_Example:19"};
	this.sidHashMap["Motor_Model__Discrete_Example:19"] = {rtwname: "<S1>/Voltage"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "Motor_Model__Discrete_Example:9"};
	this.sidHashMap["Motor_Model__Discrete_Example:9"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Add1"] = {sid: "Motor_Model__Discrete_Example:10"};
	this.sidHashMap["Motor_Model__Discrete_Example:10"] = {rtwname: "<S1>/Add1"};
	this.rtwnameHashMap["<S1>/Damping"] = {sid: "Motor_Model__Discrete_Example:11"};
	this.sidHashMap["Motor_Model__Discrete_Example:11"] = {rtwname: "<S1>/Damping"};
	this.rtwnameHashMap["<S1>/Discrete-Time Integrator"] = {sid: "Motor_Model__Discrete_Example:31"};
	this.sidHashMap["Motor_Model__Discrete_Example:31"] = {rtwname: "<S1>/Discrete-Time Integrator"};
	this.rtwnameHashMap["<S1>/Discrete-Time Integrator1"] = {sid: "Motor_Model__Discrete_Example:32"};
	this.sidHashMap["Motor_Model__Discrete_Example:32"] = {rtwname: "<S1>/Discrete-Time Integrator1"};
	this.rtwnameHashMap["<S1>/Inductance"] = {sid: "Motor_Model__Discrete_Example:7"};
	this.sidHashMap["Motor_Model__Discrete_Example:7"] = {rtwname: "<S1>/Inductance"};
	this.rtwnameHashMap["<S1>/Inertia"] = {sid: "Motor_Model__Discrete_Example:8"};
	this.sidHashMap["Motor_Model__Discrete_Example:8"] = {rtwname: "<S1>/Inertia"};
	this.rtwnameHashMap["<S1>/Ke"] = {sid: "Motor_Model__Discrete_Example:15"};
	this.sidHashMap["Motor_Model__Discrete_Example:15"] = {rtwname: "<S1>/Ke"};
	this.rtwnameHashMap["<S1>/Kt"] = {sid: "Motor_Model__Discrete_Example:12"};
	this.sidHashMap["Motor_Model__Discrete_Example:12"] = {rtwname: "<S1>/Kt"};
	this.rtwnameHashMap["<S1>/Resistance"] = {sid: "Motor_Model__Discrete_Example:14"};
	this.sidHashMap["Motor_Model__Discrete_Example:14"] = {rtwname: "<S1>/Resistance"};
	this.rtwnameHashMap["<S1>/Speed"] = {sid: "Motor_Model__Discrete_Example:20"};
	this.sidHashMap["Motor_Model__Discrete_Example:20"] = {rtwname: "<S1>/Speed"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
